name = "test-memory"
type = "webpack"
account_id = "" # You can leave this blank for Pages projects
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[site]
bucket = ".next"
entry-point = "."

[build]
command = "npm run build"
upload.format = "service-worker"

# Environment variables
[vars]
NODE_VERSION = "18"
NEXT_RUNTIME = "edge"

# This is for Cloudflare Pages
[pages_build_output_dir]
value = ".next"

[env.production]
# Production-specific settings
workers_dev = false

[env.development]
# Development-specific settings
workers_dev = true 