name = "test-memory"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Environment variables
[vars]
NODE_VERSION = "18"
NEXT_RUNTIME = "edge"

[env.production]
# Production-specific settings
workers_dev = false

[env.development]
# Development-specific settings
workers_dev = true 